-- =============================================================================
-- CNIPAC — 21 : découpage administratif du Cameroun
--
-- FICHIER GÉNÉRÉ — ne pas modifier à la main.
-- Source : docs/aw2T2qSbuxp3GQdm3wdySZ.xlsx, feuille `choices`.
-- Générateur : scripts/generer-seed-depuis-xlsform.py
-- Volumétrie : 10 régions, 58 départements, 290 arrondissements.
--
-- Le SRS §12.10 annonce « ~360 communes » ; le formulaire en recense
-- 290. C'est le formulaire qui fait foi pour l'ingestion :
-- un arrondissement absent d'ici ne peut pas être soumis depuis le terrain.
-- =============================================================================
SET search_path TO cnipac, public;

-- Racine nationale : parent de toutes les régions.
INSERT INTO unite_admin (code, libelle, niveau, parent_id, code_kobo) VALUES
  ('CM', 'Cameroun', 'national', NULL, NULL)
ON CONFLICT (code) DO NOTHING;

-- Régions (10) — liste `region` du XLSForm
INSERT INTO unite_admin (code, libelle, niveau, parent_id, code_kobo) VALUES
  ('CM-ADAMAOUA', 'Adamaoua', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'adamaoua'),
  ('CM-CENTRE', 'Centre', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'centre'),
  ('CM-EST', 'Est', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'est'),
  ('CM-EXTREMENORD', 'Extrême-Nord', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'extreme_nord'),
  ('CM-LITTORAL', 'Littoral', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'littoral'),
  ('CM-NORD', 'Nord', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'nord'),
  ('CM-NORDOUEST', 'Nord-Ouest', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'nord_ouest'),
  ('CM-OUEST', 'Ouest', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'ouest'),
  ('CM-SUD', 'Sud', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'sud'),
  ('CM-SUDOUEST', 'Sud-Ouest', 'region',
   (SELECT id FROM unite_admin WHERE code = 'CM'), 'sud_ouest')
ON CONFLICT (code) DO NOTHING;

-- Départements (58) — rattachés par la colonne `region`
INSERT INTO unite_admin (code, libelle, niveau, parent_id, code_kobo) VALUES
  ('CM-D-DJEREM', 'Djérem', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'adamaoua' AND niveau = 'region'),
   'djerem'),
  ('CM-D-FAROETDEO', 'Faro-et-Déo', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'adamaoua' AND niveau = 'region'),
   'faro_et_deo'),
  ('CM-D-MAYOBANYO', 'Mayo-Banyo', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'adamaoua' AND niveau = 'region'),
   'mayo_banyo'),
  ('CM-D-MBERE', 'Mbéré', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'adamaoua' AND niveau = 'region'),
   'mbere'),
  ('CM-D-VINA', 'Vina', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'adamaoua' AND niveau = 'region'),
   'vina'),
  ('CM-D-HAUTESANAGA', 'Haute-Sanaga', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'haute_sanaga'),
  ('CM-D-LEKIE', 'Lékié', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'lekie'),
  ('CM-D-MBAMINOUBOU', 'Mbam-et-Inoubou', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'mbam_inoubou'),
  ('CM-D-MBAMKIM', 'Mbam-et-Kim', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'mbam_kim'),
  ('CM-D-MEFOUAFAMBA', 'Méfou-et-Afamba', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'mefou_afamba'),
  ('CM-D-MEFOUAKONO', 'Méfou-et-Akono', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'mefou_akono'),
  ('CM-D-MFOUNDI', 'Mfoundi', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'mfoundi'),
  ('CM-D-NYONGKELLE', 'Nyong-et-Kellé', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'nyong_kelle'),
  ('CM-D-NYONGMFOUMOU', 'Nyong-et-Mfoumou', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'nyong_mfoumou'),
  ('CM-D-NYONGSOO', 'Nyong-et-So''o', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'centre' AND niveau = 'region'),
   'nyong_soo'),
  ('CM-D-BOUMBANGOKO', 'Boumba-et-Ngoko', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'est' AND niveau = 'region'),
   'boumba_ngoko'),
  ('CM-D-HAUTNYONG', 'Haut-Nyong', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'est' AND niveau = 'region'),
   'haut_nyong'),
  ('CM-D-KADEY', 'Kadey', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'est' AND niveau = 'region'),
   'kadey'),
  ('CM-D-LOMDJEREM', 'Lom-et-Djérem', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'est' AND niveau = 'region'),
   'lom_djerem'),
  ('CM-D-DIAMARE', 'Diamaré', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'extreme_nord' AND niveau = 'region'),
   'diamare'),
  ('CM-D-LOGONECHARI', 'Logone-et-Chari', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'extreme_nord' AND niveau = 'region'),
   'logone_chari'),
  ('CM-D-MAYODANAY', 'Mayo-Danay', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'extreme_nord' AND niveau = 'region'),
   'mayo_danay'),
  ('CM-D-MAYOKANI', 'Mayo-Kani', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'extreme_nord' AND niveau = 'region'),
   'mayo_kani'),
  ('CM-D-MAYOSAVA', 'Mayo-Sava', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'extreme_nord' AND niveau = 'region'),
   'mayo_sava'),
  ('CM-D-MAYOTSANAGA', 'Mayo-Tsanaga', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'extreme_nord' AND niveau = 'region'),
   'mayo_tsanaga'),
  ('CM-D-MOUNGO', 'Moungo', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'littoral' AND niveau = 'region'),
   'moungo'),
  ('CM-D-NKAM', 'Nkam', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'littoral' AND niveau = 'region'),
   'nkam'),
  ('CM-D-SANAGAMARITIME', 'Sanaga-Maritime', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'littoral' AND niveau = 'region'),
   'sanaga_maritime'),
  ('CM-D-WOURI', 'Wouri', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'littoral' AND niveau = 'region'),
   'wouri'),
  ('CM-D-BENOUE', 'Bénoué', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord' AND niveau = 'region'),
   'benoue'),
  ('CM-D-FARO', 'Faro', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord' AND niveau = 'region'),
   'faro'),
  ('CM-D-MAYOLOUTI', 'Mayo-Louti', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord' AND niveau = 'region'),
   'mayo_louti'),
  ('CM-D-MAYOREY', 'Mayo-Rey', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord' AND niveau = 'region'),
   'mayo_rey'),
  ('CM-D-BOYO', 'Boyo', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord_ouest' AND niveau = 'region'),
   'boyo'),
  ('CM-D-BUI', 'Bui', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord_ouest' AND niveau = 'region'),
   'bui'),
  ('CM-D-DONGAMANTUNG', 'Donga-Mantung', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord_ouest' AND niveau = 'region'),
   'donga_mantung'),
  ('CM-D-MENCHUM', 'Menchum', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord_ouest' AND niveau = 'region'),
   'menchum'),
  ('CM-D-MEZAM', 'Mezam', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord_ouest' AND niveau = 'region'),
   'mezam'),
  ('CM-D-MOMO', 'Momo', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord_ouest' AND niveau = 'region'),
   'momo'),
  ('CM-D-NGOKETUNJIA', 'Ngo-Ketunjia', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nord_ouest' AND niveau = 'region'),
   'ngo_ketunjia'),
  ('CM-D-BAMBOUTOS', 'Bamboutos', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ouest' AND niveau = 'region'),
   'bamboutos'),
  ('CM-D-HAUTNKAM', 'Haut-Nkam', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ouest' AND niveau = 'region'),
   'haut_nkam'),
  ('CM-D-HAUTSPLATEAUX', 'Hauts-Plateaux', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ouest' AND niveau = 'region'),
   'hauts_plateaux'),
  ('CM-D-KOUNGKHI', 'Koung-Khi', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ouest' AND niveau = 'region'),
   'koung_khi'),
  ('CM-D-MENOUA', 'Menoua', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ouest' AND niveau = 'region'),
   'menoua'),
  ('CM-D-MIFI', 'Mifi', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ouest' AND niveau = 'region'),
   'mifi'),
  ('CM-D-NDE', 'Ndé', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ouest' AND niveau = 'region'),
   'nde'),
  ('CM-D-NOUN', 'Noun', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ouest' AND niveau = 'region'),
   'noun'),
  ('CM-D-DJALOBO', 'Dja-et-Lobo', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud' AND niveau = 'region'),
   'dja_lobo'),
  ('CM-D-MVILA', 'Mvila', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud' AND niveau = 'region'),
   'mvila'),
  ('CM-D-OCEAN', 'Océan', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud' AND niveau = 'region'),
   'ocean'),
  ('CM-D-VALLEENTEM', 'Vallée-du-Ntem', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud' AND niveau = 'region'),
   'vallee_ntem'),
  ('CM-D-FAKO', 'Fako', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud_ouest' AND niveau = 'region'),
   'fako'),
  ('CM-D-KOUPEMANENGOUB', 'Koupé-Manengouba', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud_ouest' AND niveau = 'region'),
   'koupe_manengouba'),
  ('CM-D-LEBIALEM', 'Lebialem', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud_ouest' AND niveau = 'region'),
   'lebialem'),
  ('CM-D-MANYU', 'Manyu', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud_ouest' AND niveau = 'region'),
   'manyu'),
  ('CM-D-MEME', 'Meme', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud_ouest' AND niveau = 'region'),
   'meme'),
  ('CM-D-NDIAN', 'Ndian', 'departement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sud_ouest' AND niveau = 'region'),
   'ndian')
ON CONFLICT (code) DO NOTHING;

-- Arrondissements (290) — rattachés par la colonne `departement`
INSERT INTO unite_admin (code, libelle, niveau, parent_id, code_kobo) VALUES
  ('CM-A-TIBATI', 'Tibati', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'djerem' AND niveau = 'departement'),
   'tibati'),
  ('CM-A-NGAOUNDAL', 'Ngaoundal', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'djerem' AND niveau = 'departement'),
   'ngaoundal'),
  ('CM-A-MBAKAOU', 'Mbakaou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'djerem' AND niveau = 'departement'),
   'mbakaou'),
  ('CM-A-TIGNERE', 'Tignère', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'faro_et_deo' AND niveau = 'departement'),
   'tignere'),
  ('CM-A-GALIMTIGNERE', 'Galim-Tignère', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'faro_et_deo' AND niveau = 'departement'),
   'galim_tignere'),
  ('CM-A-KONTCHA', 'Kontcha', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'faro_et_deo' AND niveau = 'departement'),
   'kontcha'),
  ('CM-A-MAYOBALEO', 'Mayo-Baléo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'faro_et_deo' AND niveau = 'departement'),
   'mayo_baleo'),
  ('CM-A-BANYO', 'Banyo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_banyo' AND niveau = 'departement'),
   'banyo'),
  ('CM-A-BANKIM', 'Bankim', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_banyo' AND niveau = 'departement'),
   'bankim'),
  ('CM-A-MAYODARLE', 'Mayo-Darle', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_banyo' AND niveau = 'departement'),
   'mayo_darle'),
  ('CM-A-MEIGANGA', 'Meiganga', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbere' AND niveau = 'departement'),
   'meiganga'),
  ('CM-A-DJOHONG', 'Djohong', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbere' AND niveau = 'departement'),
   'djohong'),
  ('CM-A-NGAOUI', 'Ngaoui', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbere' AND niveau = 'departement'),
   'ngaoui'),
  ('CM-A-DIR', 'Dir', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbere' AND niveau = 'departement'),
   'dir'),
  ('CM-A-NGAOUNDERE1', 'Ngaoundéré 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vina' AND niveau = 'departement'),
   'ngaoundere_1'),
  ('CM-A-NGAOUNDERE2', 'Ngaoundéré 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vina' AND niveau = 'departement'),
   'ngaoundere_2'),
  ('CM-A-NGAOUNDERE3', 'Ngaoundéré 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vina' AND niveau = 'departement'),
   'ngaoundere_3'),
  ('CM-A-BELEL', 'Belel', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vina' AND niveau = 'departement'),
   'belel'),
  ('CM-A-MARTAP', 'Martap', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vina' AND niveau = 'departement'),
   'martap'),
  ('CM-A-NYAMBAKA', 'Nyambaka', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vina' AND niveau = 'departement'),
   'nyambaka'),
  ('CM-A-NGANHA', 'Nganha', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vina' AND niveau = 'departement'),
   'nganha'),
  ('CM-A-NANGAEBOKO', 'Nanga-Eboko', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haute_sanaga' AND niveau = 'departement'),
   'nanga_eboko'),
  ('CM-A-MINTA', 'Minta', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haute_sanaga' AND niveau = 'departement'),
   'minta'),
  ('CM-A-LEMBEYEZOUM', 'Lembe-Yezoum', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haute_sanaga' AND niveau = 'departement'),
   'lembe_yezoum'),
  ('CM-A-NKOTENG', 'Nkoteng', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haute_sanaga' AND niveau = 'departement'),
   'nkoteng'),
  ('CM-A-NSEM', 'Nsem', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haute_sanaga' AND niveau = 'departement'),
   'nsem'),
  ('CM-A-MONATELE', 'Monatélé', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lekie' AND niveau = 'departement'),
   'monatele'),
  ('CM-A-SAA', 'Sa''a', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lekie' AND niveau = 'departement'),
   'saa'),
  ('CM-A-EVODOULA', 'Evodoula', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lekie' AND niveau = 'departement'),
   'evodoula'),
  ('CM-A-OBALA', 'Obala', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lekie' AND niveau = 'departement'),
   'obala'),
  ('CM-A-SOA', 'Soa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lekie' AND niveau = 'departement'),
   'soa'),
  ('CM-A-BIYEM', 'Biyem', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lekie' AND niveau = 'departement'),
   'biyem'),
  ('CM-A-ELIGMFOMO', 'Elig-Mfomo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lekie' AND niveau = 'departement'),
   'elig_mfomo'),
  ('CM-A-BAFIA', 'Bafia', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_inoubou' AND niveau = 'departement'),
   'bafia'),
  ('CM-A-BOKITO', 'Bokito', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_inoubou' AND niveau = 'departement'),
   'bokito'),
  ('CM-A-OMBESSA', 'Ombessa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_inoubou' AND niveau = 'departement'),
   'ombessa'),
  ('CM-A-NDIKINIMEKI', 'Ndikiniméki', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_inoubou' AND niveau = 'departement'),
   'ndikinimeki'),
  ('CM-A-KIIKI', 'Kiiki', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_inoubou' AND niveau = 'departement'),
   'kiiki'),
  ('CM-A-KONYAMBETTA', 'Kon-Yambetta', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_inoubou' AND niveau = 'departement'),
   'kon_yambetta'),
  ('CM-A-NTUI', 'Ntui', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_kim' AND niveau = 'departement'),
   'ntui'),
  ('CM-A-YOKO', 'Yoko', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_kim' AND niveau = 'departement'),
   'yoko'),
  ('CM-A-NGORO', 'Ngoro', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_kim' AND niveau = 'departement'),
   'ngoro'),
  ('CM-A-MBANGASSINA', 'Mbangassina', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mbam_kim' AND niveau = 'departement'),
   'mbangassina'),
  ('CM-A-MFOU', 'Mfou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_afamba' AND niveau = 'departement'),
   'mfou'),
  ('CM-A-AWAE', 'Awaé', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_afamba' AND niveau = 'departement'),
   'awae'),
  ('CM-A-NKOLAFAMBA', 'Nkolafamba', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_afamba' AND niveau = 'departement'),
   'nkolafamba'),
  ('CM-A-ESSE', 'Esse', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_afamba' AND niveau = 'departement'),
   'esse'),
  ('CM-A-AFANLOUM', 'Afanloum', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_afamba' AND niveau = 'departement'),
   'afanloum'),
  ('CM-A-MENGONG', 'Mengong', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_afamba' AND niveau = 'departement'),
   'mengong'),
  ('CM-A-NGOMEDZAP', 'Ngomedzap', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_akono' AND niveau = 'departement'),
   'ngomedzap'),
  ('CM-A-AKONO', 'Akono', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_akono' AND niveau = 'departement'),
   'akono'),
  ('CM-A-NGOUMOU', 'Ngoumou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_akono' AND niveau = 'departement'),
   'ngoumou'),
  ('CM-A-DZENG', 'Dzeng', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mefou_akono' AND niveau = 'departement'),
   'dzeng'),
  ('CM-A-YAOUNDE1', 'Yaoundé 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mfoundi' AND niveau = 'departement'),
   'yaounde_1'),
  ('CM-A-YAOUNDE2', 'Yaoundé 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mfoundi' AND niveau = 'departement'),
   'yaounde_2'),
  ('CM-A-YAOUNDE3', 'Yaoundé 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mfoundi' AND niveau = 'departement'),
   'yaounde_3'),
  ('CM-A-YAOUNDE4', 'Yaoundé 4ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mfoundi' AND niveau = 'departement'),
   'yaounde_4'),
  ('CM-A-YAOUNDE5', 'Yaoundé 5ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mfoundi' AND niveau = 'departement'),
   'yaounde_5'),
  ('CM-A-YAOUNDE6', 'Yaoundé 6ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mfoundi' AND niveau = 'departement'),
   'yaounde_6'),
  ('CM-A-YAOUNDE7', 'Yaoundé 7ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mfoundi' AND niveau = 'departement'),
   'yaounde_7'),
  ('CM-A-ESEKA', 'Eseka', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_kelle' AND niveau = 'departement'),
   'eseka'),
  ('CM-A-MAKAK', 'Makak', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_kelle' AND niveau = 'departement'),
   'makak'),
  ('CM-A-BOUMNYEBEL', 'Boumnyebel', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_kelle' AND niveau = 'departement'),
   'boumnyebel'),
  ('CM-A-DIBANG', 'Dibang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_kelle' AND niveau = 'departement'),
   'dibang'),
  ('CM-A-NGOGMAPUBI', 'Ngog-Mapubi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_kelle' AND niveau = 'departement'),
   'ngog_mapubi'),
  ('CM-A-AKONOLINGA', 'Akonolinga', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_mfoumou' AND niveau = 'departement'),
   'akonolinga'),
  ('CM-A-AYOS', 'Ayos', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_mfoumou' AND niveau = 'departement'),
   'ayos'),
  ('CM-A-ENDOM', 'Endom', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_mfoumou' AND niveau = 'departement'),
   'endom'),
  ('CM-A-MENGUEMECM', 'Mengueme', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_mfoumou' AND niveau = 'departement'),
   'mengueme_cm'),
  ('CM-A-MBALMAYO', 'Mbalmayo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_soo' AND niveau = 'departement'),
   'mbalmayo'),
  ('CM-A-MENGUEMENS', 'Mengueme', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_soo' AND niveau = 'departement'),
   'mengueme_ns'),
  ('CM-A-BIKOK', 'Bikok', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_soo' AND niveau = 'departement'),
   'bikok'),
  ('CM-A-NGOMEDZAPNS', 'Ngomedzap', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nyong_soo' AND niveau = 'departement'),
   'ngomedzap_ns'),
  ('CM-A-MOLOUNDOU', 'Moloundou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'boumba_ngoko' AND niveau = 'departement'),
   'moloundou'),
  ('CM-A-YOKADOUMA', 'Yokadouma', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'boumba_ngoko' AND niveau = 'departement'),
   'yokadouma'),
  ('CM-A-GARIGOMBO', 'Gari Gombo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'boumba_ngoko' AND niveau = 'departement'),
   'gari_gombo'),
  ('CM-A-SALAPOUMBE', 'Salapoumbé', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'boumba_ngoko' AND niveau = 'departement'),
   'salapoumbe'),
  ('CM-A-ABONGMBANG', 'Abong-Mbang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nyong' AND niveau = 'departement'),
   'abong_mbang'),
  ('CM-A-DOUME', 'Doumé', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nyong' AND niveau = 'departement'),
   'doume'),
  ('CM-A-LOMIE', 'Lomié', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nyong' AND niveau = 'departement'),
   'lomie'),
  ('CM-A-NGUELEMENDOUKA', 'Nguelemendouka', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nyong' AND niveau = 'departement'),
   'nguelemendouka'),
  ('CM-A-MINDOUROU', 'Mindourou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nyong' AND niveau = 'departement'),
   'mindourou'),
  ('CM-A-MESSAMENA', 'Messamena', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nyong' AND niveau = 'departement'),
   'messamena'),
  ('CM-A-SOMALOMO', 'Somalomo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nyong' AND niveau = 'departement'),
   'somalomo'),
  ('CM-A-NGOYLA', 'Ngoyla', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nyong' AND niveau = 'departement'),
   'ngoyla'),
  ('CM-A-BATOURI', 'Batouri', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'kadey' AND niveau = 'departement'),
   'batouri'),
  ('CM-A-KETTE', 'Ketté', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'kadey' AND niveau = 'departement'),
   'kette'),
  ('CM-A-MBANGKADEY', 'Mbang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'kadey' AND niveau = 'departement'),
   'mbang_kadey'),
  ('CM-A-NDELELE', 'Ndelele', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'kadey' AND niveau = 'departement'),
   'ndelele'),
  ('CM-A-KENTZOU', 'Kentzou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'kadey' AND niveau = 'departement'),
   'kentzou'),
  ('CM-A-BERTOUA1', 'Bertoua 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lom_djerem' AND niveau = 'departement'),
   'bertoua_1'),
  ('CM-A-BERTOUA2', 'Bertoua 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lom_djerem' AND niveau = 'departement'),
   'bertoua_2'),
  ('CM-A-BELABO', 'Bélabo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lom_djerem' AND niveau = 'departement'),
   'belabo'),
  ('CM-A-DOUMAINTANG', 'Doumaintang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lom_djerem' AND niveau = 'departement'),
   'doumaintang'),
  ('CM-A-DIANG', 'Diang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lom_djerem' AND niveau = 'departement'),
   'diang'),
  ('CM-A-NANGAEBEKO', 'Nanga-Ebéko', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lom_djerem' AND niveau = 'departement'),
   'nanga_ebeko'),
  ('CM-A-MAROUA1', 'Maroua 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'diamare' AND niveau = 'departement'),
   'maroua_1'),
  ('CM-A-MAROUA2', 'Maroua 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'diamare' AND niveau = 'departement'),
   'maroua_2'),
  ('CM-A-MAROUA3', 'Maroua 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'diamare' AND niveau = 'departement'),
   'maroua_3'),
  ('CM-A-GAZAWA', 'Gazawa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'diamare' AND niveau = 'departement'),
   'gazawa'),
  ('CM-A-MERI', 'Meri', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'diamare' AND niveau = 'departement'),
   'meri'),
  ('CM-A-BOGO', 'Bogo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'diamare' AND niveau = 'departement'),
   'bogo'),
  ('CM-A-DARGALA', 'Dargala', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'diamare' AND niveau = 'departement'),
   'dargala'),
  ('CM-A-KOUSSERI', 'Kousseri', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'logone_chari' AND niveau = 'departement'),
   'kousseri'),
  ('CM-A-FOTOKOL', 'Fotokol', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'logone_chari' AND niveau = 'departement'),
   'fotokol'),
  ('CM-A-MAKARY', 'Makary', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'logone_chari' AND niveau = 'departement'),
   'makary'),
  ('CM-A-HILEALIFA', 'Hile Alifa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'logone_chari' AND niveau = 'departement'),
   'hile_alifa'),
  ('CM-A-LOGONEBIRNI', 'Logone-Birni', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'logone_chari' AND niveau = 'departement'),
   'logone_birni'),
  ('CM-A-ZINA', 'Zina', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'logone_chari' AND niveau = 'departement'),
   'zina'),
  ('CM-A-YAGOUA', 'Yagoua', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_danay' AND niveau = 'departement'),
   'yagoua'),
  ('CM-A-MAGA', 'Maga', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_danay' AND niveau = 'departement'),
   'maga'),
  ('CM-A-WINA', 'Wina', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_danay' AND niveau = 'departement'),
   'wina'),
  ('CM-A-KARHAY', 'Kar-Hay', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_danay' AND niveau = 'departement'),
   'kar_hay'),
  ('CM-A-VELE', 'Vélé', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_danay' AND niveau = 'departement'),
   'vele'),
  ('CM-A-KALFOU', 'Kalfou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_danay' AND niveau = 'departement'),
   'kalfou'),
  ('CM-A-KAELE', 'Kaélé', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_kani' AND niveau = 'departement'),
   'kaele'),
  ('CM-A-GUIDIGUIS', 'Guidiguis', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_kani' AND niveau = 'departement'),
   'guidiguis'),
  ('CM-A-MINDIF', 'Mindif', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_kani' AND niveau = 'departement'),
   'mindif'),
  ('CM-A-MOUTOURWA', 'Moutourwa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_kani' AND niveau = 'departement'),
   'moutourwa'),
  ('CM-A-GOLOMBE', 'Golombé', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_kani' AND niveau = 'departement'),
   'golombe'),
  ('CM-A-MORA', 'Mora', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_sava' AND niveau = 'departement'),
   'mora'),
  ('CM-A-KOLOFATA', 'Kolofata', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_sava' AND niveau = 'departement'),
   'kolofata'),
  ('CM-A-TOKOMBERE', 'Tokombéré', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_sava' AND niveau = 'departement'),
   'tokombere'),
  ('CM-A-MOKOLO', 'Mokolo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_tsanaga' AND niveau = 'departement'),
   'mokolo'),
  ('CM-A-KOZA', 'Koza', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_tsanaga' AND niveau = 'departement'),
   'koza'),
  ('CM-A-MOGODE', 'Mogode', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_tsanaga' AND niveau = 'departement'),
   'mogode'),
  ('CM-A-BOURHA', 'Bourha', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_tsanaga' AND niveau = 'departement'),
   'bourha'),
  ('CM-A-HINA', 'Hina', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_tsanaga' AND niveau = 'departement'),
   'hina'),
  ('CM-A-ROUA', 'Roua', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_tsanaga' AND niveau = 'departement'),
   'roua'),
  ('CM-A-NKONGSAMBA1', 'Nkongsamba 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'nkongsamba_1'),
  ('CM-A-NKONGSAMBA2', 'Nkongsamba 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'nkongsamba_2'),
  ('CM-A-NKONGSAMBA3', 'Nkongsamba 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'nkongsamba_3'),
  ('CM-A-LOUM', 'Loum', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'loum'),
  ('CM-A-MBANGA', 'Mbanga', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'mbanga'),
  ('CM-A-MELONG', 'Melong', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'melong'),
  ('CM-A-MANJO', 'Manjo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'manjo'),
  ('CM-A-NLONAKO', 'Nlonako', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'nlonako'),
  ('CM-A-MOMBO', 'Mombo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'moungo' AND niveau = 'departement'),
   'mombo'),
  ('CM-A-YABASSI', 'Yabassi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nkam' AND niveau = 'departement'),
   'yabassi'),
  ('CM-A-NKONDJOCK', 'Nkondjock', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nkam' AND niveau = 'departement'),
   'nkondjock'),
  ('CM-A-YINGUI', 'Yingui', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nkam' AND niveau = 'departement'),
   'yingui'),
  ('CM-A-NDOM', 'Ndom', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nkam' AND niveau = 'departement'),
   'ndom'),
  ('CM-A-EDEA1', 'Edéa 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sanaga_maritime' AND niveau = 'departement'),
   'edea_1'),
  ('CM-A-EDEA2', 'Edéa 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sanaga_maritime' AND niveau = 'departement'),
   'edea_2'),
  ('CM-A-POUMA', 'Pouma', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sanaga_maritime' AND niveau = 'departement'),
   'pouma'),
  ('CM-A-DIZANGUE', 'Dizangué', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sanaga_maritime' AND niveau = 'departement'),
   'dizangue'),
  ('CM-A-NYANON', 'Nyanon', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sanaga_maritime' AND niveau = 'departement'),
   'nyanon'),
  ('CM-A-NGAMBE', 'Ngambe', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sanaga_maritime' AND niveau = 'departement'),
   'ngambe'),
  ('CM-A-MOUANKO', 'Mouanko', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'sanaga_maritime' AND niveau = 'departement'),
   'mouanko'),
  ('CM-A-DOUALA1', 'Douala 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'wouri' AND niveau = 'departement'),
   'douala_1'),
  ('CM-A-DOUALA2', 'Douala 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'wouri' AND niveau = 'departement'),
   'douala_2'),
  ('CM-A-DOUALA3', 'Douala 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'wouri' AND niveau = 'departement'),
   'douala_3'),
  ('CM-A-DOUALA4', 'Douala 4ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'wouri' AND niveau = 'departement'),
   'douala_4'),
  ('CM-A-DOUALA5', 'Douala 5ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'wouri' AND niveau = 'departement'),
   'douala_5'),
  ('CM-A-DOUALA6', 'Douala 6ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'wouri' AND niveau = 'departement'),
   'douala_6'),
  ('CM-A-GAROUA1', 'Garoua 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'benoue' AND niveau = 'departement'),
   'garoua_1'),
  ('CM-A-GAROUA2', 'Garoua 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'benoue' AND niveau = 'departement'),
   'garoua_2'),
  ('CM-A-GAROUA3', 'Garoua 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'benoue' AND niveau = 'departement'),
   'garoua_3'),
  ('CM-A-NGONG', 'Ngong', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'benoue' AND niveau = 'departement'),
   'ngong'),
  ('CM-A-PITOA', 'Pitoa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'benoue' AND niveau = 'departement'),
   'pitoa'),
  ('CM-A-TCHEBOA', 'Tchéboa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'benoue' AND niveau = 'departement'),
   'tcheboa'),
  ('CM-A-BIBEMI', 'Bibemi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'benoue' AND niveau = 'departement'),
   'bibemi'),
  ('CM-A-LAGDO', 'Lagdo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'benoue' AND niveau = 'departement'),
   'lagdo'),
  ('CM-A-POLI', 'Poli', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'faro' AND niveau = 'departement'),
   'poli'),
  ('CM-A-BEKA', 'Beka', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'faro' AND niveau = 'departement'),
   'beka'),
  ('CM-A-GUIDER', 'Guider', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_louti' AND niveau = 'departement'),
   'guider'),
  ('CM-A-FIGUIL', 'Figuil', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_louti' AND niveau = 'departement'),
   'figuil'),
  ('CM-A-MAYOOULO', 'Mayo-Oulo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_louti' AND niveau = 'departement'),
   'mayo_oulo'),
  ('CM-A-DEMSA', 'Demsa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_louti' AND niveau = 'departement'),
   'demsa'),
  ('CM-A-TOUBORO', 'Touboro', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_rey' AND niveau = 'departement'),
   'touboro'),
  ('CM-A-TCHOLLIRE', 'Tcholliré', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_rey' AND niveau = 'departement'),
   'tchollire'),
  ('CM-A-MADINGRING', 'Madingring', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_rey' AND niveau = 'departement'),
   'madingring'),
  ('CM-A-REYBOUBA', 'Rey-Bouba', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_rey' AND niveau = 'departement'),
   'rey_bouba'),
  ('CM-A-MBAIBOUM', 'Mbaiboum', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mayo_rey' AND niveau = 'departement'),
   'mbaiboum'),
  ('CM-A-FUNDONG', 'Fundong', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'boyo' AND niveau = 'departement'),
   'fundong'),
  ('CM-A-BELO', 'Belo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'boyo' AND niveau = 'departement'),
   'belo'),
  ('CM-A-NJINIKOM', 'Njinikom', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'boyo' AND niveau = 'departement'),
   'njinikom'),
  ('CM-A-KUMBO', 'Kumbo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bui' AND niveau = 'departement'),
   'kumbo'),
  ('CM-A-JAKIRI', 'Jakiri', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bui' AND niveau = 'departement'),
   'jakiri'),
  ('CM-A-OKU', 'Oku', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bui' AND niveau = 'departement'),
   'oku'),
  ('CM-A-NKAMBEBUI', 'Nkambe', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bui' AND niveau = 'departement'),
   'nkambe_bui'),
  ('CM-A-NONI', 'Noni', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bui' AND niveau = 'departement'),
   'noni'),
  ('CM-A-NKAMBEDM', 'Nkambe', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'donga_mantung' AND niveau = 'departement'),
   'nkambe_dm'),
  ('CM-A-AKO', 'Ako', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'donga_mantung' AND niveau = 'departement'),
   'ako'),
  ('CM-A-MISAJE', 'Misaje', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'donga_mantung' AND niveau = 'departement'),
   'misaje'),
  ('CM-A-NWA', 'Nwa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'donga_mantung' AND niveau = 'departement'),
   'nwa'),
  ('CM-A-WUM', 'Wum', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menchum' AND niveau = 'departement'),
   'wum'),
  ('CM-A-BEFANG', 'Befang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menchum' AND niveau = 'departement'),
   'befang'),
  ('CM-A-ZHOA', 'Zhoa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menchum' AND niveau = 'departement'),
   'zhoa'),
  ('CM-A-FUNGOM', 'Fungom', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menchum' AND niveau = 'departement'),
   'fungom'),
  ('CM-A-BAMENDA1', 'Bamenda 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mezam' AND niveau = 'departement'),
   'bamenda_1'),
  ('CM-A-BAMENDA2', 'Bamenda 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mezam' AND niveau = 'departement'),
   'bamenda_2'),
  ('CM-A-BAMENDA3', 'Bamenda 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mezam' AND niveau = 'departement'),
   'bamenda_3'),
  ('CM-A-SANTA', 'Santa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mezam' AND niveau = 'departement'),
   'santa'),
  ('CM-A-TUBAH', 'Tubah', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mezam' AND niveau = 'departement'),
   'tubah'),
  ('CM-A-BAFUT', 'Bafut', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mezam' AND niveau = 'departement'),
   'bafut'),
  ('CM-A-MBENGWI', 'Mbengwi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'momo' AND niveau = 'departement'),
   'mbengwi'),
  ('CM-A-BATIBO', 'Batibo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'momo' AND niveau = 'departement'),
   'batibo'),
  ('CM-A-WIDIKUM', 'Widikum', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'momo' AND niveau = 'departement'),
   'widikum'),
  ('CM-A-NJIKWA', 'Njikwa', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'momo' AND niveau = 'departement'),
   'njikwa'),
  ('CM-A-NDOP', 'Ndop', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ngo_ketunjia' AND niveau = 'departement'),
   'ndop'),
  ('CM-A-BABESSI', 'Babessi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ngo_ketunjia' AND niveau = 'departement'),
   'babessi'),
  ('CM-A-BALIKUMBAT', 'Balikumbat', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ngo_ketunjia' AND niveau = 'departement'),
   'balikumbat'),
  ('CM-A-MBOUDA', 'Mbouda', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bamboutos' AND niveau = 'departement'),
   'mbouda'),
  ('CM-A-BABADJOU', 'Babadjou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bamboutos' AND niveau = 'departement'),
   'babadjou'),
  ('CM-A-BATCHAM', 'Batcham', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bamboutos' AND niveau = 'departement'),
   'batcham'),
  ('CM-A-GALIM', 'Galim', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bamboutos' AND niveau = 'departement'),
   'galim'),
  ('CM-A-BATIE', 'Batié', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'bamboutos' AND niveau = 'departement'),
   'batie'),
  ('CM-A-BAFANG', 'Bafang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nkam' AND niveau = 'departement'),
   'bafang'),
  ('CM-A-BAKOU', 'Bakou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nkam' AND niveau = 'departement'),
   'bakou'),
  ('CM-A-BANDJA', 'Bandja', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nkam' AND niveau = 'departement'),
   'bandja'),
  ('CM-A-BANA', 'Bana', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nkam' AND niveau = 'departement'),
   'bana'),
  ('CM-A-KEKEM', 'Kekem', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'haut_nkam' AND niveau = 'departement'),
   'kekem'),
  ('CM-A-BAHAM', 'Baham', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'hauts_plateaux' AND niveau = 'departement'),
   'baham'),
  ('CM-A-BANGOU', 'Bangou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'hauts_plateaux' AND niveau = 'departement'),
   'bangou'),
  ('CM-A-BANGANGTEHP', 'Bangangté', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'hauts_plateaux' AND niveau = 'departement'),
   'bangangte_hp'),
  ('CM-A-BAYANGAM', 'Bayangam', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'koung_khi' AND niveau = 'departement'),
   'bayangam'),
  ('CM-A-KOUTABA', 'Koutaba', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'koung_khi' AND niveau = 'departement'),
   'koutaba'),
  ('CM-A-MALANTOUEN', 'Malantouen', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'koung_khi' AND niveau = 'departement'),
   'malantouen'),
  ('CM-A-DSCHANG', 'Dschang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menoua' AND niveau = 'departement'),
   'dschang'),
  ('CM-A-FOKOUE', 'Fokoué', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menoua' AND niveau = 'departement'),
   'fokoue'),
  ('CM-A-NKONGZEM', 'Nkong-Zem', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menoua' AND niveau = 'departement'),
   'nkong_zem'),
  ('CM-A-PENKAMICHEL', 'Penka-Michel', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menoua' AND niveau = 'departement'),
   'penka_michel'),
  ('CM-A-SANTCHOU', 'Santchou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'menoua' AND niveau = 'departement'),
   'santchou'),
  ('CM-A-BAFOUSSAM1', 'Bafoussam 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mifi' AND niveau = 'departement'),
   'bafoussam_1'),
  ('CM-A-BAFOUSSAM2', 'Bafoussam 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mifi' AND niveau = 'departement'),
   'bafoussam_2'),
  ('CM-A-BAFOUSSAM3', 'Bafoussam 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mifi' AND niveau = 'departement'),
   'bafoussam_3'),
  ('CM-A-BANGANGTENDE', 'Bangangté', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nde' AND niveau = 'departement'),
   'bangangte_nde'),
  ('CM-A-BAZOU', 'Bazou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nde' AND niveau = 'departement'),
   'bazou'),
  ('CM-A-TONGA', 'Tonga', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'nde' AND niveau = 'departement'),
   'tonga'),
  ('CM-A-FOUMBAN', 'Foumban', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'noun' AND niveau = 'departement'),
   'foumban'),
  ('CM-A-FOUMBOT', 'Foumbot', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'noun' AND niveau = 'departement'),
   'foumbot'),
  ('CM-A-KOUOPTAMO', 'Kouoptamo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'noun' AND niveau = 'departement'),
   'kouoptamo'),
  ('CM-A-MASSANGAM', 'Massangam', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'noun' AND niveau = 'departement'),
   'massangam'),
  ('CM-A-NJIMOM', 'Njimom', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'noun' AND niveau = 'departement'),
   'njimom'),
  ('CM-A-MAGBA', 'Magba', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'noun' AND niveau = 'departement'),
   'magba'),
  ('CM-A-BANGOURAIN', 'Bangourain', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'noun' AND niveau = 'departement'),
   'bangourain'),
  ('CM-A-SANGMELIMA', 'Sangmélima', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'dja_lobo' AND niveau = 'departement'),
   'sangmelima'),
  ('CM-A-BENGBIS', 'Bengbis', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'dja_lobo' AND niveau = 'departement'),
   'bengbis'),
  ('CM-A-DJOUM', 'Djoum', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'dja_lobo' AND niveau = 'departement'),
   'djoum'),
  ('CM-A-MEYOMESSALA', 'Meyomessala', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'dja_lobo' AND niveau = 'departement'),
   'meyomessala'),
  ('CM-A-MINTOM', 'Mintom', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'dja_lobo' AND niveau = 'departement'),
   'mintom'),
  ('CM-A-OVENG', 'Oveng', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'dja_lobo' AND niveau = 'departement'),
   'oveng'),
  ('CM-A-EBOLOWA1', 'Ebolowa 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mvila' AND niveau = 'departement'),
   'ebolowa_1'),
  ('CM-A-EBOLOWA2', 'Ebolowa 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mvila' AND niveau = 'departement'),
   'ebolowa_2'),
  ('CM-A-BIYOUHA', 'Biyouha', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mvila' AND niveau = 'departement'),
   'biyouha'),
  ('CM-A-EFOULAN', 'Efoulan', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mvila' AND niveau = 'departement'),
   'efoulan'),
  ('CM-A-MVANGUE', 'Mvangué', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mvila' AND niveau = 'departement'),
   'mvangue'),
  ('CM-A-NGOULEMAKONG', 'Ngoulemakong', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'mvila' AND niveau = 'departement'),
   'ngoulemakong'),
  ('CM-A-KRIBI1', 'Kribi 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ocean' AND niveau = 'departement'),
   'kribi_1'),
  ('CM-A-KRIBI2', 'Kribi 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ocean' AND niveau = 'departement'),
   'kribi_2'),
  ('CM-A-CAMPO', 'Campo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ocean' AND niveau = 'departement'),
   'campo'),
  ('CM-A-LOKOUNDJE', 'Lokoundjé', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ocean' AND niveau = 'departement'),
   'lokoundje'),
  ('CM-A-BIPINDI', 'Bipindi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ocean' AND niveau = 'departement'),
   'bipindi'),
  ('CM-A-AKOM2', 'Akom II', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ocean' AND niveau = 'departement'),
   'akom_2'),
  ('CM-A-LOLODORF', 'Lolodorf', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ocean' AND niveau = 'departement'),
   'lolodorf'),
  ('CM-A-AMBAM', 'Ambam', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vallee_ntem' AND niveau = 'departement'),
   'ambam'),
  ('CM-A-MAAN', 'Ma''an', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vallee_ntem' AND niveau = 'departement'),
   'maan'),
  ('CM-A-OLAMZE', 'Olamze', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vallee_ntem' AND niveau = 'departement'),
   'olamze'),
  ('CM-A-KYEOSSI', 'Kyé-Ossi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'vallee_ntem' AND niveau = 'departement'),
   'kye_ossi'),
  ('CM-A-LIMBE1', 'Limbe 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'fako' AND niveau = 'departement'),
   'limbe_1'),
  ('CM-A-LIMBE2', 'Limbe 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'fako' AND niveau = 'departement'),
   'limbe_2'),
  ('CM-A-LIMBE3', 'Limbe 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'fako' AND niveau = 'departement'),
   'limbe_3'),
  ('CM-A-BUEA', 'Buea', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'fako' AND niveau = 'departement'),
   'buea'),
  ('CM-A-TIKO', 'Tiko', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'fako' AND niveau = 'departement'),
   'tiko'),
  ('CM-A-MUYUKA', 'Muyuka', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'fako' AND niveau = 'departement'),
   'muyuka'),
  ('CM-A-WESTCOAST', 'West Coast', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'fako' AND niveau = 'departement'),
   'west_coast'),
  ('CM-A-BANGEM', 'Bangem', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'koupe_manengouba' AND niveau = 'departement'),
   'bangem'),
  ('CM-A-NGUTI', 'Nguti', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'koupe_manengouba' AND niveau = 'departement'),
   'nguti'),
  ('CM-A-TOMBEL', 'Tombel', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'koupe_manengouba' AND niveau = 'departement'),
   'tombel'),
  ('CM-A-KONYEKM', 'Konye', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'koupe_manengouba' AND niveau = 'departement'),
   'konye_km'),
  ('CM-A-ALOU', 'Alou', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lebialem' AND niveau = 'departement'),
   'alou'),
  ('CM-A-FONTEM', 'Fontem', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lebialem' AND niveau = 'departement'),
   'fontem'),
  ('CM-A-WABANE', 'Wabane', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'lebialem' AND niveau = 'departement'),
   'wabane'),
  ('CM-A-MAMFE', 'Mamfe', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'manyu' AND niveau = 'departement'),
   'mamfe'),
  ('CM-A-AKWAYA', 'Akwaya', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'manyu' AND niveau = 'departement'),
   'akwaya'),
  ('CM-A-EYUMOJOCK', 'Eyumojock', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'manyu' AND niveau = 'departement'),
   'eyumojock'),
  ('CM-A-TINTO', 'Tinto', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'manyu' AND niveau = 'departement'),
   'tinto'),
  ('CM-A-UPPERBAYANG', 'Upper-Bayang', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'manyu' AND niveau = 'departement'),
   'upper_bayang'),
  ('CM-A-KUMBA1', 'Kumba 1er', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'meme' AND niveau = 'departement'),
   'kumba_1'),
  ('CM-A-KUMBA2', 'Kumba 2ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'meme' AND niveau = 'departement'),
   'kumba_2'),
  ('CM-A-KUMBA3', 'Kumba 3ème', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'meme' AND niveau = 'departement'),
   'kumba_3'),
  ('CM-A-KONYEMEME', 'Konye', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'meme' AND niveau = 'departement'),
   'konye_meme'),
  ('CM-A-MBONGE', 'Mbonge', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'meme' AND niveau = 'departement'),
   'mbonge'),
  ('CM-A-EKONDOTITI', 'Ekondo-Titi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ndian' AND niveau = 'departement'),
   'ekondo_titi'),
  ('CM-A-MUNDEMBA', 'Mundemba', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ndian' AND niveau = 'departement'),
   'mundemba'),
  ('CM-A-ISANGELE', 'Isangele', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ndian' AND niveau = 'departement'),
   'isangele'),
  ('CM-A-BAMUSSO', 'Bamusso', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ndian' AND niveau = 'departement'),
   'bamusso'),
  ('CM-A-KOMBOABEDIMO', 'Kombo-Abedimo', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ndian' AND niveau = 'departement'),
   'kombo_abedimo'),
  ('CM-A-KOMBOITINDI', 'Kombo-Itindi', 'arrondissement',
   (SELECT id FROM unite_admin WHERE code_kobo = 'ndian' AND niveau = 'departement'),
   'kombo_itindi')
ON CONFLICT (code) DO NOTHING;

-- Contrôle d'intégrité : aucune unité orpheline ne doit subsister.
DO $$
DECLARE v_orphelins INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_orphelins FROM unite_admin
   WHERE niveau <> 'national' AND parent_id IS NULL;
  IF v_orphelins > 0 THEN
    RAISE EXCEPTION '% unité(s) administrative(s) sans parent : hiérarchie incohérente', v_orphelins;
  END IF;
END $$;
